In [1]:
import numpy as np
ss=np.array([11,3,8])
print(ss)


[11  3  8]


In [2]:
s=np.array([(11,4,5),(5,66,3)])
print(s)

[[11  4  5]
 [ 5 66  3]]


In [3]:
print(s.ndim)

2


In [4]:
print(s.itemsize)

4


In [5]:
print(s.dtype)

int32


In [6]:
print(s.size)

6


In [7]:
ar=np.array([(1,2,3,4),(5,6,7,8)])
ar=ar.reshape(4,2)
print(ar)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0, :])
print(a[0:,2])

[1 2 3 4]
[3 5]


In [9]:
ls1=np.linspace(1,5,15)
print(ls1)

[1.         1.28571429 1.57142857 1.85714286 2.14285714 2.42857143
 2.71428571 3.         3.28571429 3.57142857 3.85714286 4.14285714
 4.42857143 4.71428571 5.        ]


In [10]:
az=np.array([(1,22,7,8),(3,4,5,6)])
print(np.sqrt(az))

[[1.         4.69041576 2.64575131 2.82842712]
 [1.73205081 2.         2.23606798 2.44948974]]


In [11]:
ad=np.array([(1,2,3,4),(3,4,5,6)])
ad1=np.array([(1,2,3,4),(3,4,5,6)])
print(ad+ad1)

[[ 2  4  6  8]
 [ 6  8 10 12]]


In [12]:
print(ad-ad1)

[[0 0 0 0]
 [0 0 0 0]]


In [13]:
print(ad*ad1)

[[ 1  4  9 16]
 [ 9 16 25 36]]


In [14]:
print(ad/ad1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
print(np.vstack((ad,ad1)))

[[1 2 3 4]
 [3 4 5 6]
 [1 2 3 4]
 [3 4 5 6]]


In [16]:
print(np.hstack((ad,ad1)))

[[1 2 3 4 1 2 3 4]
 [3 4 5 6 3 4 5 6]]


In [17]:
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
d=np.full((3,3),1,dtype='complex')
print(d)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [19]:
e=np.random.random((4,2))
print(e)

[[0.27710264 0.71595635]
 [0.87261857 0.4107143 ]
 [0.98181638 0.35441286]
 [0.56585981 0.82245257]]


In [20]:
s=np.arange(0,50,10)

In [21]:
print(s)

[ 0 10 20 30 40]


In [22]:
flatten=ad.flatten()

In [23]:
print(flatten)

[1 2 3 4 3 4 5 6]


# pandas


In [24]:
import pandas as pd
import numpy as np


In [25]:
m=pd.Series([2,3,4,5,6,7,np.nan,9,6])
m

0    2.0
1    3.0
2    4.0
3    5.0
4    6.0
5    7.0
6    NaN
7    9.0
8    6.0
dtype: float64

In [26]:
s=pd.Series([1,2,3,4,5,6,np.nan,8,9,10])

In [27]:
s

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     NaN
7     8.0
8     9.0
9    10.0
dtype: float64

In [28]:
dd=pd.date_range('20220729',periods=11)

In [29]:
dd

DatetimeIndex(['2022-07-29', '2022-07-30', '2022-07-31', '2022-08-01',
               '2022-08-02', '2022-08-03', '2022-08-04', '2022-08-05',
               '2022-08-06', '2022-08-07', '2022-08-08'],
              dtype='datetime64[ns]', freq='D')

In [30]:
df=pd.DataFrame(np.random.randn(11,4),index=dd,columns=['a','b','c','d'])

In [31]:
df

a         b         c         d
2022-07-29 -0.303906  0.623395 -1.721284 -0.410127
2022-07-30  1.514594  0.788200 -0.280448  1.103265
2022-07-31  0.776446  0.539641  0.454580  0.145046
2022-08-01 -0.029790 -0.454201 -0.976376  0.845638
2022-08-02 -0.048172  0.673289 -0.757747 -0.127853
2022-08-03 -2.045337 -0.274734 -0.630461  1.517140
2022-08-04  1.370399  0.053237  1.103222 -0.175332
2022-08-05  0.718519  0.084447 -0.338849 -0.436841
2022-08-06 -0.332367  0.270342 -0.350372  0.731370
2022-08-07  0.589942  0.288992  1.670710  0.240577
2022-08-08 -0.344840  0.443438 -0.780292  2.748729

In [32]:
dd1=pd.DataFrame({'a'
                 'b':pd.date_range('20220729',periods=10),
                 'c':pd.Series(1,index=list(range(10)),dtype='float32'),
                 'd':np.array([5]*10,dtype='int32'),
                 'e':pd.Categorical(['true','false','true','false','true','false','true','false','true','false']),
                 'f':'nottttt'})

dd1

ab    c  d      e        f
0 2022-07-29  1.0  5   true  nottttt
1 2022-07-30  1.0  5  false  nottttt
2 2022-07-31  1.0  5   true  nottttt
3 2022-08-01  1.0  5  false  nottttt
4 2022-08-02  1.0  5   true  nottttt
5 2022-08-03  1.0  5  false  nottttt
6 2022-08-04  1.0  5   true  nottttt
7 2022-08-05  1.0  5  false  nottttt
8 2022-08-06  1.0  5   true  nottttt
9 2022-08-07  1.0  5  false  nottttt

In [33]:
dd1.dtypes

ab    datetime64[ns]
c            float32
d              int32
e           category
f             object
dtype: object

In [34]:
dd1.head()


#upper 5 values can see

ab    c  d      e        f
0 2022-07-29  1.0  5   true  nottttt
1 2022-07-30  1.0  5  false  nottttt
2 2022-07-31  1.0  5   true  nottttt
3 2022-08-01  1.0  5  false  nottttt
4 2022-08-02  1.0  5   true  nottttt

In [35]:
dd1.tail()

#lower 5 values can seee

ab    c  d      e        f
5 2022-08-03  1.0  5  false  nottttt
6 2022-08-04  1.0  5   true  nottttt
7 2022-08-05  1.0  5  false  nottttt
8 2022-08-06  1.0  5   true  nottttt
9 2022-08-07  1.0  5  false  nottttt

In [36]:
dd1.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [37]:
dd1.to_numpy()

array([[Timestamp('2022-07-29 00:00:00'), 1.0, 5, 'true', 'nottttt'],
       [Timestamp('2022-07-30 00:00:00'), 1.0, 5, 'false', 'nottttt'],
       [Timestamp('2022-07-31 00:00:00'), 1.0, 5, 'true', 'nottttt'],
       [Timestamp('2022-08-01 00:00:00'), 1.0, 5, 'false', 'nottttt'],
       [Timestamp('2022-08-02 00:00:00'), 1.0, 5, 'true', 'nottttt'],
       [Timestamp('2022-08-03 00:00:00'), 1.0, 5, 'false', 'nottttt'],
       [Timestamp('2022-08-04 00:00:00'), 1.0, 5, 'true', 'nottttt'],
       [Timestamp('2022-08-05 00:00:00'), 1.0, 5, 'false', 'nottttt'],
       [Timestamp('2022-08-06 00:00:00'), 1.0, 5, 'true', 'nottttt'],
       [Timestamp('2022-08-07 00:00:00'), 1.0, 5, 'false', 'nottttt']],
      dtype=object)

In [38]:
dd1.describe()

c     d
count  10.0  10.0
mean    1.0   5.0
std     0.0   0.0
min     1.0   5.0
25%     1.0   5.0
50%     1.0   5.0
75%     1.0   5.0
max     1.0   5.0

In [39]:
dd1.sort_index(axis=1,ascending=False)

f      e  d    c         ab
0  nottttt   true  5  1.0 2022-07-29
1  nottttt  false  5  1.0 2022-07-30
2  nottttt   true  5  1.0 2022-07-31
3  nottttt  false  5  1.0 2022-08-01
4  nottttt   true  5  1.0 2022-08-02
5  nottttt  false  5  1.0 2022-08-03
6  nottttt   true  5  1.0 2022-08-04
7  nottttt  false  5  1.0 2022-08-05
8  nottttt   true  5  1.0 2022-08-06
9  nottttt  false  5  1.0 2022-08-07

In [40]:
df.sort_values(by='c')

a         b         c         d
2022-07-29 -0.303906  0.623395 -1.721284 -0.410127
2022-08-01 -0.029790 -0.454201 -0.976376  0.845638
2022-08-08 -0.344840  0.443438 -0.780292  2.748729
2022-08-02 -0.048172  0.673289 -0.757747 -0.127853
2022-08-03 -2.045337 -0.274734 -0.630461  1.517140
2022-08-06 -0.332367  0.270342 -0.350372  0.731370
2022-08-05  0.718519  0.084447 -0.338849 -0.436841
2022-07-30  1.514594  0.788200 -0.280448  1.103265
2022-07-31  0.776446  0.539641  0.454580  0.145046
2022-08-04  1.370399  0.053237  1.103222 -0.175332
2022-08-07  0.589942  0.288992  1.670710  0.240577

In [41]:
df['c']

2022-07-29   -1.721284
2022-07-30   -0.280448
2022-07-31    0.454580
2022-08-01   -0.976376
2022-08-02   -0.757747
2022-08-03   -0.630461
2022-08-04    1.103222
2022-08-05   -0.338849
2022-08-06   -0.350372
2022-08-07    1.670710
2022-08-08   -0.780292
Freq: D, Name: c, dtype: float64

In [42]:
df[0:3]
#pic the first 3 coloms

a         b         c         d
2022-07-29 -0.303906  0.623395 -1.721284 -0.410127
2022-07-30  1.514594  0.788200 -0.280448  1.103265
2022-07-31  0.776446  0.539641  0.454580  0.145046

In [43]:
df.loc[:,['a','c']]

a         c
2022-07-29 -0.303906 -1.721284
2022-07-30  1.514594 -0.280448
2022-07-31  0.776446  0.454580
2022-08-01 -0.029790 -0.976376
2022-08-02 -0.048172 -0.757747
2022-08-03 -2.045337 -0.630461
2022-08-04  1.370399  1.103222
2022-08-05  0.718519 -0.338849
2022-08-06 -0.332367 -0.350372
2022-08-07  0.589942  1.670710
2022-08-08 -0.344840 -0.780292

In [44]:
df.loc['20220729',['d','c']]

d   -0.410127
c   -1.721284
Name: 2022-07-29 00:00:00, dtype: float64

In [45]:
df.iloc[3]

a   -0.029790
b   -0.454201
c   -0.976376
d    0.845638
Name: 2022-08-01 00:00:00, dtype: float64

In [46]:
df.iloc[3:5]

a         b         c         d
2022-08-01 -0.029790 -0.454201 -0.976376  0.845638
2022-08-02 -0.048172  0.673289 -0.757747 -0.127853

In [47]:
df[df['a']>0]

a         b         c         d
2022-07-30  1.514594  0.788200 -0.280448  1.103265
2022-07-31  0.776446  0.539641  0.454580  0.145046
2022-08-04  1.370399  0.053237  1.103222 -0.175332
2022-08-05  0.718519  0.084447 -0.338849 -0.436841
2022-08-07  0.589942  0.288992  1.670710  0.240577

In [48]:
df2=df.reindex(index=d[0:4],columns=list(df.columns)+['e'])


In [49]:
df2

a   b   c   d   e
((1+0j), (1+0j), (1+0j)) NaN NaN NaN NaN NaN
((1+0j), (1+0j), (1+0j)) NaN NaN NaN NaN NaN
((1+0j), (1+0j), (1+0j)) NaN NaN NaN NaN NaN

In [50]:
df2

a   b   c   d   e
((1+0j), (1+0j), (1+0j)) NaN NaN NaN NaN NaN
((1+0j), (1+0j), (1+0j)) NaN NaN NaN NaN NaN
((1+0j), (1+0j), (1+0j)) NaN NaN NaN NaN NaN

In [51]:
df2.fillna(value=2)

a    b    c    d    e
((1+0j), (1+0j), (1+0j))  2.0  2.0  2.0  2.0  2.0
((1+0j), (1+0j), (1+0j))  2.0  2.0  2.0  2.0  2.0
((1+0j), (1+0j), (1+0j))  2.0  2.0  2.0  2.0  2.0

In [52]:



s

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     NaN
7     8.0
8     9.0
9    10.0
dtype: float64

In [53]:
df.apply(np.cumsum)

a         b         c         d
2022-07-29 -0.303906  0.623395 -1.721284 -0.410127
2022-07-30  1.210688  1.411595 -2.001732  0.693138
2022-07-31  1.987134  1.951236 -1.547152  0.838184
2022-08-01  1.957344  1.497035 -2.523528  1.683822
2022-08-02  1.909172  2.170324 -3.281276  1.555969
2022-08-03 -0.136166  1.895589 -3.911737  3.073109
2022-08-04  1.234234  1.948826 -2.808515  2.897777
2022-08-05  1.952753  2.033273 -3.147364  2.460936
2022-08-06  1.620386  2.303616 -3.497736  3.192306
2022-08-07  2.210329  2.592608 -1.827027  3.432883
2022-08-08  1.865489  3.036046 -2.607319  6.181612

In [54]:
df.apply(lambda x: x.min())

a   -2.045337
b   -0.454201
c   -1.721284
d   -0.436841
dtype: float64

In [55]:
dk=pd.DataFrame(np.random.randn(10,4))

In [56]:
dk

0         1         2         3
0  0.223318 -0.978100 -0.287642 -1.237568
1  0.706462 -0.212231 -0.785159 -0.811657
2  0.501254 -0.501127  0.912042 -0.176508
3 -1.814286  0.614624  0.852595 -0.742780
4  0.321430 -1.037891  0.017789 -0.430701
5 -0.634689  2.413071 -0.535830 -0.340689
6 -0.070875  0.316446 -0.764818  0.111305
7  0.178851 -0.464898  2.469598  0.664659
8 -0.024257  0.236805 -0.006868 -0.887229
9  3.163843  0.575668  0.142987 -0.742187

In [57]:
d=[df[:3],df[3:7],df[7:]]

In [58]:
d

[                   a         b         c         d
 2022-07-29 -0.303906  0.623395 -1.721284 -0.410127
 2022-07-30  1.514594  0.788200 -0.280448  1.103265
 2022-07-31  0.776446  0.539641  0.454580  0.145046,
                    a         b         c         d
 2022-08-01 -0.029790 -0.454201 -0.976376  0.845638
 2022-08-02 -0.048172  0.673289 -0.757747 -0.127853
 2022-08-03 -2.045337 -0.274734 -0.630461  1.517140
 2022-08-04  1.370399  0.053237  1.103222 -0.175332,
                    a         b         c         d
 2022-08-05  0.718519  0.084447 -0.338849 -0.436841
 2022-08-06 -0.332367  0.270342 -0.350372  0.731370
 2022-08-07  0.589942  0.288992  1.670710  0.240577
 2022-08-08 -0.344840  0.443438 -0.780292  2.748729]

In [59]:
pd.concat(d)

a         b         c         d
2022-07-29 -0.303906  0.623395 -1.721284 -0.410127
2022-07-30  1.514594  0.788200 -0.280448  1.103265
2022-07-31  0.776446  0.539641  0.454580  0.145046
2022-08-01 -0.029790 -0.454201 -0.976376  0.845638
2022-08-02 -0.048172  0.673289 -0.757747 -0.127853
2022-08-03 -2.045337 -0.274734 -0.630461  1.517140
2022-08-04  1.370399  0.053237  1.103222 -0.175332
2022-08-05  0.718519  0.084447 -0.338849 -0.436841
2022-08-06 -0.332367  0.270342 -0.350372  0.731370
2022-08-07  0.589942  0.288992  1.670710  0.240577
2022-08-08 -0.344840  0.443438 -0.780292  2.748729

In [60]:
l=pd.DataFrame({'a':[1,2],'b':[3,4]})

In [61]:
r=pd.DataFrame({'b':[2,3],'d':[3,5]})

In [62]:
l

a  b
0  1  3
1  2  4

In [63]:
r

b  d
0  2  3
1  3  5

In [64]:
pd.merge(l,r,on='b')

a  b  d
0  1  3  5

In [65]:
df

a         b         c         d
2022-07-29 -0.303906  0.623395 -1.721284 -0.410127
2022-07-30  1.514594  0.788200 -0.280448  1.103265
2022-07-31  0.776446  0.539641  0.454580  0.145046
2022-08-01 -0.029790 -0.454201 -0.976376  0.845638
2022-08-02 -0.048172  0.673289 -0.757747 -0.127853
2022-08-03 -2.045337 -0.274734 -0.630461  1.517140
2022-08-04  1.370399  0.053237  1.103222 -0.175332
2022-08-05  0.718519  0.084447 -0.338849 -0.436841
2022-08-06 -0.332367  0.270342 -0.350372  0.731370
2022-08-07  0.589942  0.288992  1.670710  0.240577
2022-08-08 -0.344840  0.443438 -0.780292  2.748729

In [66]:
df.groupby(['a','b']).sum()

c         d
a         b                            
-2.045337 -0.274734 -0.630461  1.517140
-0.344840  0.443438 -0.780292  2.748729
-0.332367  0.270342 -0.350372  0.731370
-0.303906  0.623395 -1.721284 -0.410127
-0.048172  0.673289 -0.757747 -0.127853
-0.029790 -0.454201 -0.976376  0.845638
 0.589942  0.288992  1.670710  0.240577
 0.718519  0.084447 -0.338849 -0.436841
 0.776446  0.539641  0.454580  0.145046
 1.370399  0.053237  1.103222 -0.175332
 1.514594  0.788200 -0.280448  1.103265

In [67]:
tu=list(zip(*[[1,2,3,4,5,6,7,8],[8,7,6,5,4,3,2,1]]))
index=pd.MultiIndex.from_tuples(tu,names=['first','Second'])
f=pd.DataFrame(np.random.randn(8,4),index=index,columns=['A','B','c','d'])



In [68]:
f

A         B         c         d
first Second                                        
1     8       0.716744  1.307791 -1.036447  1.022413
2     7       0.378428 -0.113967 -0.679795  1.359958
3     6      -0.604408 -0.453530 -0.993310 -0.744061
4     5      -1.061994 -0.948825  0.173144 -1.763525
5     4       2.580060 -0.215529  1.021734  1.361128
6     3      -0.677462 -0.116540  0.671707  0.587065
7     2      -0.798112  0.198363 -0.950621 -1.535746
8     1       1.060408  0.269577  2.508279  0.113915

In [69]:
f.stack()

first  Second   
1      8       A    0.716744
               B    1.307791
               c   -1.036447
               d    1.022413
2      7       A    0.378428
               B   -0.113967
               c   -0.679795
               d    1.359958
3      6       A   -0.604408
               B   -0.453530
               c   -0.993310
               d   -0.744061
4      5       A   -1.061994
               B   -0.948825
               c    0.173144
               d   -1.763525
5      4       A    2.580060
               B   -0.215529
               c    1.021734
               d    1.361128
6      3       A   -0.677462
               B   -0.116540
               c    0.671707
               d    0.587065
7      2       A   -0.798112
               B    0.198363
               c   -0.950621
               d   -1.535746
8      1       A    1.060408
               B    0.269577
               c    2.508279
               d    0.113915
dtype: float64

In [70]:
f.unstack()

A                                                             \
Second         1         2         3        4         5         6         7   
first                                                                         
1            NaN       NaN       NaN      NaN       NaN       NaN       NaN   
2            NaN       NaN       NaN      NaN       NaN       NaN  0.378428   
3            NaN       NaN       NaN      NaN       NaN -0.604408       NaN   
4            NaN       NaN       NaN      NaN -1.061994       NaN       NaN   
5            NaN       NaN       NaN  2.58006       NaN       NaN       NaN   
6            NaN       NaN -0.677462      NaN       NaN       NaN       NaN   
7            NaN -0.798112       NaN      NaN       NaN       NaN       NaN   
8       1.060408       NaN       NaN      NaN       NaN       NaN       NaN   

                         B            ...         c                   d  \
Second         8         1         2  ...         7         8         1   
first                                 ...                                 
1       0.716744       NaN       NaN  ...       NaN -1.036447       NaN   
2            NaN       NaN       NaN  ... -0.679795       NaN       NaN   
3            NaN       NaN       NaN  ...       NaN       NaN       NaN   
4            NaN       NaN       NaN  ...       NaN       NaN       NaN   
5            NaN       NaN       NaN  ...       NaN       NaN       NaN   
6            NaN       NaN       NaN  ...       NaN       NaN       NaN   
7            NaN       NaN  0.198363  ...       NaN       NaN       NaN   
8            NaN  0.269577       NaN  ...       NaN       NaN  0.113915   

                                                                              
Second         2         3         4         5         6         7         8  
first                                                                         
1            NaN       NaN       NaN       NaN       NaN       NaN  1.022413  
2            NaN       NaN       NaN       NaN       NaN  1.359958       NaN  
3            NaN       NaN       NaN       NaN -0.744061       NaN       NaN  
4            NaN       NaN       NaN -1.763525       NaN       NaN       NaN  
5            NaN       NaN  1.361128       NaN       NaN       NaN       NaN  
6            NaN  0.587065       NaN       NaN       NaN       NaN       NaN  
7      -1.535746       NaN       NaN       NaN       NaN       NaN       NaN  
8            NaN       NaN       NaN       NaN       NaN       NaN       NaN  

[8 rows x 32 columns]

In [71]:
date=pd.date_range('29/07/2022, 01:40',periods=5,freq='S')
date


DatetimeIndex(['2022-07-29 01:40:00', '2022-07-29 01:40:01',
               '2022-07-29 01:40:02', '2022-07-29 01:40:03',
               '2022-07-29 01:40:04'],
              dtype='datetime64[ns]', freq='S')

In [72]:
ts=pd.Series(np.random.randint(len(date)),date)

In [73]:
ts

2022-07-29 01:40:00    2
2022-07-29 01:40:01    2
2022-07-29 01:40:02    2
2022-07-29 01:40:03    2
2022-07-29 01:40:04    2
Freq: S, dtype: int64

In [74]:
ts=ts.tz_localize('UTC')
ts

2022-07-29 01:40:00+00:00    2
2022-07-29 01:40:01+00:00    2
2022-07-29 01:40:02+00:00    2
2022-07-29 01:40:03+00:00    2
2022-07-29 01:40:04+00:00    2
Freq: S, dtype: int64

In [75]:
dates=pd.date_range('29/07/2021',periods=5,freq='M')
dates

C:\Users\afsal\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3369: UserWarning: Parsing '29/07/2021' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  exec(code_obj, self.user_global_ns, self.user_ns)


DatetimeIndex(['2021-07-31', '2021-08-31', '2021-09-30', '2021-10-31',
               '2021-11-30'],
              dtype='datetime64[ns]', freq='M')

In [76]:
ts=pd.Series(np.random.randint(len(dates)),dates)
ts

2021-07-31    4
2021-08-31    4
2021-09-30    4
2021-10-31    4
2021-11-30    4
Freq: M, dtype: int64

In [77]:
df=pd.DataFrame({'id':[1,2,3,4,5,6],
                "grade":['a','b','c','b','a','e']})


In [78]:
df['Grade']=df['grade'].astype('category')
df['Grade']


0    a
1    b
2    c
3    b
4    a
5    e
Name: Grade, dtype: category
Categories (4, object): ['a', 'b', 'c', 'e']

In [79]:
df['Grade'].categories=['good','very bad','very good','exelent']
df

id grade Grade
0   1     a     a
1   2     b     b
2   3     c     c
3   4     b     b
4   5     a     a
5   6     e     e

In [80]:
df

id grade Grade
0   1     a     a
1   2     b     b
2   3     c     c
3   4     b     b
4   5     a     a
5   6     e     e